service: alexa-skill-hello-world

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-1
  memorySize: 256
  cfLogs: true

functions:
  skill:
    handler: src/index.handler
    description: Alexa hello world skill
    events:
      - alexaSkill
